Bug-Fixes from PE-D
AY2223S2-CS2103T-T11-2/tp pull request #173
Opened 2023-04-01 07:39 UTC by KS2499

closes #133, #134, #135, #136, #138, #139, #141, #142, #144, #145, #152, #157, #161

### Major Changes
- Updated UserGuide order and updated some examples.
- Update DateTime format in outdated examples
- Add a minimum length of 3 and maximum length of 15 for phone numbers
    - 3 for emergeny numbers like 999
    - 15 is the current international maximum for a phone number
- Update UserGuide url in HelpWindow

2023-04-01 15:41 UTC, Beebeeoii requested changes
some minor nits. thanks for this PR !

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Optional Parameter `f/` that forces imports regardless of duplicate values.
Can we add a Note box here to emphasise that no arguments needs to be passed after `f/`

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Format: `export p/ INDEX1 p/ INDEX2`
```suggestion
Format: `export [p/INDEX]...`
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Format: `export p/ INDEX1 p/ INDEX2`
do see https://ay2223s2-cs2103t-t11-2.github.io/tp/UserGuide.html#understanding-commands

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Format: `import JSON f/`
ditto

```suggestion
Format: `import JSON [f/]`
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Format: `addm m/TITLE [p/PERSON]... dt/DATE_TIME l/LOCATION des/DESCRIPTION`
ditto

```suggestion
Format: `addm m/TITLE [p/PERSON]... [dt/DATE_TIME] [l/LOCATION] [des/DESCRIPTION]`
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* `TITLE` must be provided.
i think can remove since it is not in square brackets which denotes optionality.

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* `DATE_TIME` must be provided in the format `dd-MM-yyyy HH:mm`.
could we make a sub-section under the section `Quick Reference Guide` on `Date/Time Formats`. reason is that `dd-MM-yyyy HH:mm` is not the only accepted format.

then just insert a link here to ask the reader to refer back to that section

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* The `DATE`, `START_TIME` and `END_TIME` must be provided in the format `DD-MM-YYYY`, `HH:MM` (24-hour) respectively.
remove `START_TIME` and `END_TIME`. moreover, ditto above about how the date/time format takes a few forms...

```suggestion
* `DATE` must be provided in the format `DD-MM-YYYY`, `HH:MM` (24-hour) respectively.
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Examples:
```suggestion
Example:
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* `editm 1 t/Project Update dt/04-01-2023 10:00`  Edits the date first meeting to be on `04-01-2023`, and change its title to "Project Update".
```suggestion
* `editm 1 t/Project Update dt/04-01-2023 10:00`  Edits the date/time first meeting to be on `04-01-2023 10:00`, and changes its title to `Project Update`.
```

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* Sorts the meetings in the address book by the specified `ATTRIBUTE`, which can be one of the following: `m/` (meeting title), `dt/` (date/time), `l/` (location), or `des/` (description).
probably better to put in a table instead?

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +Sorts meetings in the currently displayed address book by a specified attribute.
let's include the fact that it sorts in ascending order?

2023-04-01 15:41 UTC, Beebeeoii commented on docs/UserGuide.md
> +* If the `r` option is included, the meetings will be sorted in reverse order.
maybe can add: `... in reverse (descending) order`

2023-04-01 16:05 UTC, Beebeeoii commented on docs/UserGuide.md
> +* `DATE_TIME` must be provided in the format `dd-MM-yyyy HH:mm`.
after #176 is merged we can just insert a link for the reader to refer to the date and time section

2023-04-03 13:34 UTC, Beebeeoii commented on src/main/java/seedu/quickcontacts/ui/HelpWindow.java
could we add a newline `/n` before `More help can be found in...` so that there is clearing break in the different segments in our help menu? something like below:

![helpMessage](https://user-images.githubusercontent.com/55170539/229525498-91d03813-8491-473f-af0a-52b03ded8848.png)

2023-04-04 16:25 UTC, Beebeeoii approved these changes
lgtm other than a few minor changes

2023-04-04 16:25 UTC, Beebeeoii commented on docs/UserGuide.md
> +</div>
could we replace this with a `TIP` box instead and then create a new `NOTE` box to say that no parameters are required for `f/`

2023-04-04 16:25 UTC, Beebeeoii commented on src/main/java/seedu/quickcontacts/ui/HelpWindow.java
> +            + "t/ tag\n\n"
shucks realised this is not allowed as it is not a bugfix... lets revert this. sorry !

2023-04-04 17:13 UTC, chuakid commented on docs/UserGuide.md
> +</div>
I will handle the parts relating to export/import 👍

2023-04-05 01:21 UTC, Beebeeoii approved these changes

2023-04-05 01:21 UTC, merged