Fix UG bugs and update my PPP
AY2223S2-CS2103T-T11-2/tp pull request #189
Opened 2023-04-05 08:42 UTC by chuakid

Fixes the following issues:

- [ ] #165
- [ ] #148 
- [ ] #172  
- [ ] #158 
- [ ] #171

2023-04-05 15:39 UTC, Beebeeoii requested changes
lgtm other than a few nits. thanks !

2023-04-05 15:39 UTC, Beebeeoii commented on docs/UserGuide.md
> +| **Mark meeting as not done** | `unmark m/INDEX`                                                                    <br/>
Mark/unmark can be done for multiple meetings at one go.

should be `mark m/INDEX [m/MORE_INDEXES]...` and `unmark m/INDEX [m/MORE_INDEXES]...`

2023-04-05 15:39 UTC, Beebeeoii commented on docs/UserGuide.md
> +Shows meetings that are not marked as done and are in the future i.e not over yet.
```suggestion
Shows meetings that are not marked as done and those that are in the future i.e not over yet.
```

2023-04-05 15:39 UTC, Beebeeoii commented on docs/UserGuide.md
> +### Showing pending meetings : `pending`
can we put a `TIP` box to tell user how to get back to the default view of all the meetings? aka tell them to use `findm` to list all

2023-04-05 15:39 UTC, Beebeeoii commented on docs/UserGuide.md
> +Format: "mark m/INDEX..." or "unmark m/INDEX..."
```suggestion
Format: "mark m/INDEX [m/MORE_INDEXES]..." or "unmark m/INDEX [m/MORE_INDEXES]..."
```

2023-04-05 15:39 UTC, Beebeeoii commented on docs/UserGuide.md
> +Marks the specified meeting as either done or undone. Meetings marked as done will have green colored titles.
can we put a `NOTE` box to emphasis that marked meetings have green titles?

2023-04-07 06:52 UTC, chuakid commented on docs/UserGuide.md
> +Marks the specified meeting as either done or undone. Meetings marked as done will have green colored titles.
Resolved 7723b1005a3a3e06d20074b506c386d038715118

2023-04-07 06:54 UTC, chuakid commented on docs/UserGuide.md
> +### Showing pending meetings : `pending`
Resolved 4a508f1

2023-04-07 06:56 UTC, chuakid commented on docs/UserGuide.md
> +| **Mark meeting as not done** | `unmark m/INDEX`                                                                    <br/>
Fixed 602e3d6

2023-04-07 14:40 UTC, merged