Export meetings
AY2223S2-CS2103T-T11-2/tp pull request #91
Opened 2023-03-23 07:43 UTC by chuakid

Implements exporting and importing of meetings.

Resolves #59

2023-03-23 09:34 UTC, KS2499 approved these changes
Thanks for the PR! All looks good

2023-03-23 11:24 UTC, Beebeeoii requested changes
some comments regarding `exportm` autocompletion behaviour, `DateTime` comparison and command feedback. thanks for this PR!

2023-03-23 11:24 UTC, Beebeeoii commented on src/main/java/seedu/address/logic/parser/ExportMeetingsParser.java
> +    }
could we do instead of having it append through all the prefixes, even if user did not fill in the argument for that prefix, we have it cycle the current unfilled prefix until user fills something?

something like: if the input is currently `exportm` and user presses `TAB`, it becomes `exportm m/`. If user does not input anything for the prefix `m/` and presses `TAB` again, it should cycle to `start/` so it becomes `exportm start/` instead of `export m/ start/`

might be helpful to take a look at `EditMeetingParser` https://github.com/AY2223S2-CS2103T-T11-2/tp/blob/0b1159119e64bfd5d3e0870c071e88ec5e797a40/src/main/java/seedu/address/logic/parser/EditMeetingParser.java#L67-L88

2023-03-23 11:24 UTC, Beebeeoii commented on src/main/java/seedu/address/model/meeting/DateTime.java
>   * TODO: Include more acceptable formats for date/time instead of just dd/MM/yyyy HH:mm
could we remove this line since it is done and you are at it? thanks !

2023-03-23 11:24 UTC, Beebeeoii commented on src/main/java/seedu/address/model/meeting/DateTime.java
> +                    + "2. Time must comply with the format: " + TIME_FORMAT + " in 24-hour format.";
could also help to update this with the new formats found below https://github.com/AY2223S2-CS2103T-T11-2/tp/blob/0b1159119e64bfd5d3e0870c071e88ec5e797a40/src/main/java/seedu/address/model/meeting/DateTime.java#L47-L53

the format can be any combination of date format and time format specified above

2023-03-23 11:24 UTC, Beebeeoii commented on src/main/java/seedu/address/model/meeting/DateTime.java
> +        return this.meetingDate.compareTo(o.meetingDate);
hmm we should also compare the time if `meetingTime` is not `null`? if one `DateTime` object has `meetingTime` and the other does not have, then it makes sense to take the one which does not have any `meetingTime` to be just `00:00` (midnight) of that specified day.

2023-03-24 08:54 UTC, chuakid commented on src/main/java/seedu/address/model/meeting/DateTime.java
> +                    + "2. Time must comply with the format: " + TIME_FORMAT + " in 24-hour format.";
Resolved with commit 526be7db2d13c916a9a497255c9b1342345f4203

2023-03-24 09:49 UTC, chuakid commented on src/main/java/seedu/address/model/meeting/DateTime.java
> +        return this.meetingDate.compareTo(o.meetingDate);
Resolved in 183c46bcc10a1304b2500bbd6be19a5a9295dd84 with datetime refactors

2023-03-24 14:08 UTC, Beebeeoii approved these changes
lgtm !

2023-03-24 14:09 UTC, merged