Branch Sort Meeting
AY2223S2-CS2103T-T11-2/tp pull request #96
Opened 2023-03-23 17:52 UTC by jeremykhoo-NUS

## Add Sort Meeting Functionality

This pull request adds the ability to sort meetings in the address book application by different attributes: datetime, location, description, and title. Users can specify which attribute to sort by using command line prefixes, and they can also choose to sort in reverse order by adding the letter "r" after the prefix.

The following changes were made to the code:

- Added a new command called SortMeetingCommand that takes in a prefix to determine which attribute to sort by and a boolean to determine if the sorting should be done in reverse order.
- Created comparator objects for each attribute that can be used to sort the meetings in the filtered meeting list.
- Implemented a switch case statement in the execute method of the SortMeetingCommand class to determine which comparator to use based on the prefix specified by the user.
- Updated the `MESSAGE_USAGE` and `MESSAGE_SUCCESS` strings to provide instructions on how to use the new command and display a message indicating which attribute the meetings were sorted by.

Please review and let me know if any changes are needed. Thank you!

2023-03-24 03:24 UTC, Beebeeoii requested changes
thanks for the PR! looks great. some a thought: sorting is default to descending order? should it be defaulted to ascending instead?

2023-03-24 03:24 UTC, Beebeeoii commented on src/main/java/seedu/address/logic/parser/SortMeetingParser.java
> +    }
How about having autocompletion that allows the user to `TAB` and cycle through the available `Prefix` to sort by? something like this: 
```suggestion
@Override
    public AutocompleteResult getAutocompleteSuggestion(String args) {
        String[] argsSplit = args.trim().split(" ");
        if (args.isEmpty()) {
            return new AutocompleteResult(PREFIXES[0], false);
        }
        String lastPrefix = argsSplit[argsSplit.length - 1];

        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(" " + lastPrefix, PREFIXES);
        boolean returnNext = false;

        for (Prefix p : PREFIXES) {
            if (returnNext) {
                return new AutocompleteResult(p, true);
            }

            if (argMultimap.getValue(p).isPresent() && p.toString().equals(lastPrefix)) {
                returnNext = true;
            }
        }

        if (!args.endsWith("/")) {
            return new AutocompleteResult(null, false);
        }

        return new AutocompleteResult(PREFIXES[0], true);
    }
```

2023-03-24 03:24 UTC, Beebeeoii commented on src/main/java/seedu/address/model/AddressBook.java
> +     * The meeting must not already exist in the address book.
ooo what does this mean haha

2023-03-24 03:24 UTC, Beebeeoii commented on src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
> +    */
```suggestion
    /**
     * Returns the number of entries in this ArgumentMultimap.
     */
```

2023-03-24 03:24 UTC, Beebeeoii commented on src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
> +    */
```suggestion
    /**
     * Returns the number of entries in this ArgumentMultimap.
     */
```

2023-03-24 14:03 UTC, Beebeeoii approved these changes
lgtm !

2023-03-27 08:30 UTC, chuakid approved these changes
LGTM

2023-03-27 09:17 UTC, merged